version: "3.4"

networks:
    internal:
        driver: bridge

services:
    app:
        networks:
            - internal
        build:
            dockerfile: app.Dockerfile
            context: ${PWD}
        restart: on-failure
        links:
            - db
            - redis
            - elasticsearch
    nginx:
        networks:
            - internal
        restart: on-failure
        build:
            dockerfile: nginx.Dockerfile
            context: ${PWD}
        links:
            - app
    db:
        networks:
            - internal
        restart: on-failure
        volumes:
            - ${PWD}/postgres_data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_DB: ${DB_DATABASE}
        image: postgres:15.2-alpine3.17
    redis:
        networks:
            - internal
        restart: on-failure
        image: redis:7.0.9-alpine3.17
    elasticsearch:
        networks:
            - internal
        ulimits:
            memlock:
                soft: -1
                hard: -1
        restart: on-failure
        image: elasticsearch:8.7.1
        volumes:
            - esdata:/usr/share/elasticsearch/data
        ports:
            - "9200:9200"
    rabbitmq:
        restart: on-failure
        image: rabbitmq:3.11.16-management-alpine
        hostname: rabbitmq
        networks:
            - internal
        volumes:
            - rabbitmq:/var/lib/rabbitmq
        environment:
            - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
            - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
        ports:
            - "15672:15672"

volumes:
    esdata:
        driver: local
    rabbitmq:
        driver: local